---
# This playbook deploys the whole application stack in this site.

- name: apply common configuration to all nodes
  hosts: all
  #remote_user: root

  roles:
    - common

- name: configure and deploy the webservers and application code
  hosts: tag_Name_Demo_Linux_Webserver
  remote_user: root

  roles:
    - web

- name: deploy MySQL and configure the databases
  hosts: tag_Name_Demo_linux_DBserver
  remote_user: root

  roles:
    - db
