# -*- mode: ruby -*-
# vi: set ft=ruby :

CENTOS = {
  box: "opscode-centos-6.5",
  virtualbox_url: "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.5_chef-provisionerless.box",
  vmware_fusion_url: "http://opscode-vm-bento.s3.amazonaws.com/vagrant/vmware/opscode_centos-6.5_chef-provisionerless.box"
}
UBUNTU = {
  box: "opscode-ubuntu-12.04",
  virtualbox_url: "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.04_chef-provisionerless.box",
  vmware_fusion_url: "http://opscode-vm-bento.s3.amazonaws.com/vagrant/vmware/opscode_ubuntu-12.04_chef-provisionerless.box"
}

VAGRANTFILE_API_VERSION = "2"
NODES = ENV["ARBY_NODES"].nil? ? 3 : ENV["ARBY_NODES"].to_i
OS = ENV["ARBY_OS"].nil? ? CENTOS : Kernel.const_get(ENV["ARBY_OS"])

Vagrant.configure(VAGRANTFILE_API_VERSION) do |cluster|
  # Utilize the Cachier plugin to cache downloaded packages.
  unless ENV["ARBY_CACHE"].nil?
    cluster.cache.auto_detect = true
  end

  cluster.vm.box = OS[:box]

  cluster.vm.provider :virtualbox do |vb, override|
    override.vm.box_url = OS[:virtualbox_url]
  end

  cluster.vm.provider :vmware_fusion do |vm, override|
    override.vm.box_url = OS[:vmware_fusion_url]
  end

  # Nodes for Riak, Riak CS, and Stanchion.
  (1..NODES).each do |index|
    last_octet = index + 5
    vm_name    = "riak-#{index}.local"

    cluster.vm.define vm_name do |config|
      config.vm.provider :virtualbox do |vb, override|
        vb.customize ["modifyvm", :id, "--memory", "1024"]
        vb.customize ["modifyvm", :id, "--cpus", "1"]
      end

      config.vm.provider :vmware_fusion do |vm, override|
        vm.vmx["memsize"] = "1024"
        vm.vmx["numvcpus"] = "1"
      end

      config.vm.hostname = vm_name
      config.vm.network :private_network, ip: "10.42.0.#{last_octet}"
    end
  end

end
