---
# This playbook deploys a simple standalone Tomcat 7 server.

- name: Deploy a simple standalone Tomcat 7 server
  hosts: tomcat-servers
  remote_user: root
  become: true
  become_method: sudo

  roles:
    - selinux
    - tomcat
